[build]
  publish = "/"

# Form handling redirects
[[redirects]]
  from = "/manual"
  to = "/manual.html"
  status = 200

[[redirects]]
  from = "/success"
  to = "/success.html"
  status = 200

# Custom 404 page
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
  
 [[redirects]]
  from = "/map"
  to   = "/map.html"
  status = 200

[[redirects]]
  from = "/map/"
  to   = "/map.html"
  status = 200
